export enum PermissionStatus {
  CHECKING = 'checking',
  GRANTED = 'GRANTED',
  DENIED = 'DENIED',
  BLOCKED = 'BLOCKED',
  LIMITED = 'LIMITED',
  UNAVAILABLE = 'UNAVAILABLE',
  UNDETERMINED = 'UNDETERMINED',
}
